### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by sindresorhus** [urish/gulp-add-src#1]
gulp 3.8 now [supports adding files midstream](https://github.com/gulpjs/gulp/blob/master/CHANGELOG.md#380) which makes this plugin moot. You might want to consider deprecating it ;)

**Comment by lehni** [comment]
I wonder if it was right to deprecate this plugin just yet. It looks like it covers use cases that `gulp.src()` since 3.8.0 does not cover, see: https://github.com/gulpjs/gulp/issues/1508
